local.baseUrl: ${LOCAL_BASE_URL}

route:
  routeAcctId: ${ROUTE_ACCT_ID}
  routeAcctList: ${ROUTE_ACCT_LIST}
  routeInvalidRouteAcctList: ${ROUTE_INVALID_ROUTE_ACCT_LIST}
  routeInvalidRouteAcctId: ${ROUTE_INVALID_ROUTE_ACCT_ID}
  routeInvalidAcctId: ${ROUTE_INVALID_ACCT_ID}
  routeValidAcctId: ${ROUTE_VALID_ACCT_ID}
  routeInvalidUuidAcctId: ${ROUTE_INVALID_UUID_ACCT_ID}